insert into Course values('Java001','Core-Java')
insert into Course values('SAP002','SAP-ABAP')
insert into Course values('JavaA003','Java-Angular')
insert into Course values('JavaR004','Java-React')
insert into Course values('Spr005','SpringBoot')
insert into Course values('SprMs006','SpringBoot Microservices')
insert into Course values('MS007','Mean Stack')
insert into Course values('AJS008','Angular JS')
insert into Course values('HCS009','HTML-CSS-BOOTSTRAP')
insert into Course values('JavaT010','Java-Testing')